# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Valid-Loose
version:      0.05
version_from: lib/Email/Valid/Loose.pm
installdirs:  site
requires:
    Email::Valid:                  0.17
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
